import { settingsSlice } from '../slices/settings.slice';

// Action creators are generated for each case reducer function
const {
  setSettings,
  syncSettings,
  syncDeviceId,
  syncConnection,
  syncPolling,
  syncNotifications,
  resetSettings,
  setContextMenus,
  saveContextMenu,
  removeContextMenu,
  resetContextMenu,
  setContentTabs,
  saveContentTab,
  removeContentTab,
  resetContentTabs,
  setQuickMenus,
  saveQuickMenu,
  removeQuickMenu,
  resetQuickMenus,
  syncInterface,
  syncDownloads,
  syncDownloadsIntercept,
  syncAdvanced,
  syncAdvancedLogging,
  setSyncSettings,
  syncTasksSettings,
  syncScrapeSettings,
  syncContentSettings,
} = settingsSlice.actions;

// Export as named constants
export {
  removeContentTab,
  removeContextMenu,
  removeQuickMenu,
  resetContentTabs,
  resetContextMenu,
  resetQuickMenus,
  resetSettings,
  saveContentTab,
  saveContextMenu,
  saveQuickMenu,
  setContentTabs,
  setContextMenus,
  setQuickMenus,
  setSettings,
  setSyncSettings,
  syncAdvanced,
  syncAdvancedLogging,
  syncConnection,
  syncContentSettings,
  syncDeviceId,
  syncDownloads,
  syncDownloadsIntercept,
  syncInterface,
  syncNotifications,
  syncPolling,
  syncScrapeSettings,
  syncSettings,
  syncTasksSettings,
};
