export {
  elapsedTime,
  getAcceptLanguages,
  getActiveTab,
  getManifest,
  HttpMethod,
  i18n,
  injectContentScripts,
  isMacOs,
  localClear,
  localGet,
  localSet,
  nullSafeCompare,
  numberCompare,
  parseJSON,
  ProxyLogger,
  rxFetch,
  stringCompare,
  syncClear,
  syncGet,
  syncSet,
  useI18n,
  versionCheck,
} from '@dvcol/web-extension-utils';

export type {
  BaseHttpRequest,
  BeforeOperator,
  BufferDebounceUnless,
  ChromeMessage,
  ChromeMessageHandler,
  ChromeResponse,
  HttpBody,
  HttpHeaders,
  HttpParameters,
  Manifest,
  SkipUntilRepeat,
} from '@dvcol/web-extension-utils';
