# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build node application

on:
  push:
    branches: [ main ]
  pull_request:

env:
  node_version: 16.x

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'

      - name: Clean install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Linting (eslint)
        run: npm run eslint

      - name: Unit tests
        run: npm run test:unit
        if: github.event_name == 'push' && github.ref == 'ref/head/main'

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && [[ ! github.actor =~ dependabot.*\[bot\] ]]

    steps:
      - name: Checkout branch ${{ github.r }}
        uses: actions/checkout@v2

      - name: Unit tests (changes only)
        uses: ArtiomTr/jest-coverage-report-action@v2.0.3
        with:
          test-script: npm run test:change
