# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release - Tag and release package

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

env:
  node_version: 16.x

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch ${{ github.ref }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js ${{ env.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: 'yarn'

      - name: Clean install dependencies
        run: yarn install

      - name: Release
        run: |
          # setup git creds
          git config user.name "GitHub Release Bot"
          git config user.email "<>"
          
          # generate release
          yarn release

      - name: Push to remote
        run: |
          # Check status
          git status
          git diff --color -U0 | cat
          
          # push changes
          git push origin --follow-tags
