# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tag and release application

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'

      - name: Clean install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Zip build folder
        run: |
          # Zipping build folder for artifact upload
          cd build;
          zip -r synology-download.zip *
          
          # Check zip created
          echo "Zip created in 'build/'"
          ls -l  synology-download.zip
          cd ..

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: build/synology-download.zip

      - name: Publish
        uses: mnao305/chrome-extension-upload@2.2.0
        with:
          extension-id: ebbdkledlkjpgbbmmopgbnnjmklnkcef
          client-id:  $CLIENT_ID
          refresh-token: $REFRESH_TOKEN
          file-path: build/extension.zip
          publish: false
        env:
          CLIENT_ID: ${{ secrets.CHROME_WEB_STORE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CHROME_WEB_STORE_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.CHROME_WEB_STORE_REFRESH_TOKEN }}

