# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tag and release application

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'

      - name: Clean install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Zip build folder
        run: |
          # Zipping build folder for artifact upload
          zip -r synology-download.zip ./build/
          ls -l synology-download.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./CHANGELOG.md
          files: ./build/synology-download.zip

  publish:
    runs-on: ubuntu-latest

#  TODO: publish to chrome store
#
