# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bumps application version

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]

env:
  node_version: 16.x

jobs:
  version:
    name: Bump version
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release)') && !contains(github.event.head_commit.message, 'chore(version)')"

    env:
      old_version: ''
      new_version: ''

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'

      - name: Bump version
        run: |
          # Save old version to env
          echo "old_version=$(jq -r .version package.json)" >> $GITHUB_ENV

          # extract commit version
          message=$(git log -1 --pretty=format:"%s")

          # install standard-version
          npm i -g standard-version

          # bump version
          npm run version

          # Save new version to env
          echo "new_version=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Write version to manifest.json
        run: |
          # Move to src folder
          cd ./src

          # Replace manifest version to align with package.json
          manifest_version=$(jq -r .version manifest.json)
          tmp=$(mktemp)
          jq --arg new_version "$new_version" '.version = $new_version' manifest.json > "$tmp" && mv "$tmp" manifest.json

          echo "Manifest version changed from '$manifest_version' to '$(jq -r .version manifest.json)'"

      - name: Commit files
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Bump Version Bot"
          git config user.email "<>"

          # Stage the file, commit and push
          git status
          git diff --color -U0 | cat
          git add package.json package-lock.json src/manifest.json
          git commit -m "chore(version): Bumping version from '${{ env.old_version }}' to '${{ env.new_version }}'"
          git push origin
